BEGIN;

ALTER TABLE userLogin ADD COLUMN cidade VARCHAR(100) NOT NULL;
ALTER TABLE userLogin ADD COLUMN tipoPessoa CHAR(1) NOT NULL DEFAULT 'f';
ALTER TABLE userLogin ADD COLUMN cpf VARCHAR(14);
ALTER TABLE userLogin ADD COLUMN cnpj VARCHAR(18);

COMMIT;